# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andreas Paradisiotis
title: Software Architect
email: a.paradisiotis@gmail.com
website: https://paradisecy.github.io
# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  paradisecy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: andreas-paradisiotis-871a9767
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/my.jpg
about_content: | # this will include new lines to allow paragraphs
  Software architect with 12+ years professional expertise with <mark>C#</mark> <mark>Python</mark> <mark>C++</mark> <mark>C</mark> <mark>Java</mark> <mark>Scala</mark> <mark>ABAP</mark> <mark>JavaScript</mark> and <mark>SQL</mark>. 
  
  Strong engineering professional focused on distributed technologies, data wrangling and machine learning. 
  
  Skilled in <mark>AWS</mark> <mark>Azure</mark> <mark>GCP</mark> <mark>Linode</mark> clouds.
  
  Seeking for opportunities where using distributed computing tech and the latest development technologies and methodologies which can satisfy the most demanding projects.
  
  Supporter and contributor of the open-source community and the open code mindset.


content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Professional Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Full Stack Developer
        link: https://nodeslinks.com/
        link_text: |
             <img src="images/nl.png" width="30px" /> 
             Nodes & Links
        # sub_title: 
        caption: 2021 - Present (Remote/Cyprus) 
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
           - Feature development into the product

           - DevOps in the NoOps team
          
           - Backend development
            
           - Working heavily with AWS cloud services.
      - layout: left
        title: Co-Founder and Owner
        link: /
        link_text: |
             <img src="images/agrosoft.png" width="100px" /> 
             AgroSoft
        # sub_title: 
        caption: 2020 - 2022 (Cyprus)
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Partner of Soft1 in Cyprus
          - Industrial & IoT solutions and analytics services
      - layout: left
        title: Senior Software Architect                       
        link: paradisiotis.com
        link_text: |
             <img src="images/para.png" width="70px" /> 
             Paradisiotis Group
        # sub_title: 
        caption: 2019 - 2021 (Cyprus)
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Architecting software for analytics, and industrial automation
      - layout: left
        title: Senior Software Developer                     
        link: horforex.com
        link_text: |
             <img src="images/hot.png" width="40px" /> 
             HotForex
        # sub_title: 
        caption: 2018 - 2019 (Cyprus)
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Full stack development with integrated data science.
          - Design develop and document new and existing features for a highly scalable distributed platform.
      - layout: left
        title: Senior Software Engineer                    
        link: tsys.com
        link_text: |
             <img src="images/tsys.png" width="40px" /> 
             TSYS
        # sub_title: 
        caption: 2017 - 2018 (Cyprus)
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Development, maintenance, and support of automation framework and administration of CI/CD process.   
      - layout: left
        title: Software Engineer                   
        link: 3cx.com
        link_text: |
             <img src="images/3cx.png" width="40px" /> 
             3CX
        # sub_title: 
        caption: 2017 (Cyprus)
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Development, maintenance, documentation and support of new and existing features for the 3CX PBX using .NET and JavaScript.   
      - layout: left
        title: Software Engineer                   
        link: https://www.preventionatsea.com/
        link_text: |
             <img src="images/pre.png" width="40px" /> 
             Prevention at sea
        # sub_title: 
        caption: 2015 - 2017 (Greece, Cyprus)
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Design, implementation, testing, deployment and maintenance of applications for the shipping industry.
      - layout: left
        title: SAP ABAP Developer / Administrator                    
        link: paradisiotis.com
        link_text: |
             <img src="images/para.png" width="70px" /> 
             Paradisiotis Group
        # sub_title: 
        caption: 2013 - 2015 (Cyprus)
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Responsible for the design, development and customization of a wide range of SAP solutions
      - layout: left
        title: Intership                   
        link: cyta.com.cy
        link_text: |
             <img src="images/cyta.png" width="40px" /> 
             Cyta Hellas
        # sub_title: 
        caption: 2012 - 2013 (Greece)
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - Internship employee as a Network Equipment Administrator and as 2nd Level/Field Network Technician
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: European University Cyprus
        caption: 2023 - pending
        sub_title: Master of Business Administration - MBA 
      - layout: left
        title: Udacity
        caption: 2018
        sub_title: Deep Learning Nanodegree
      - layout: left
        title: Open University of Cyprus & University of Cyprus
        caption: 2017 - 2021
        sub_title: Msc Cognitive Systems 
      - layout: left
        title: European University Cyprus
        caption: 2013 - 2015
        sub_title: Bsc Computer Science 
      - layout: left
        title: ATEI Piraeus Greece
        caption: 2008 - 2012
        sub_title: ‘Ptixio’ (Bsc) Automation Engineering

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Tech interests:
        -	Cognitive systems
        -	Artificial Intelligence
        -	Machine Learning
        -	Deep Learning
        -	IoT
        -	Decentralized architectures
        -	Industrial Automation

      Personal interests:
        - Playing acoustic guitar, piano
        - Music production
        - Sports (football, swimming, running, cycling, functional core training)
        - Travelling

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
